# Generated by Django 5.2.10 on 2026-01-21 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0002_remove_intern_user_intern_completed_tasks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern',
            name='department',
        ),
        migrations.RemoveField(
            model_name='intern',
            name='phone',
        ),
        migrations.AlterField(
            model_name='intern',
            name='completed_tasks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='intern',
            name='email',
            field=models.EmailField(default='temp@example.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='intern',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
